### ISSUE TITLE
Request to make a new brunch

### ISSUE THREAD

**Issue by ehsanghaffar** [ganjoor/ganjoor-musueum#7]
Hello. I visited the Ganjar Museum website. In my opinion, it needs a revision in the design.
So please create a new branch so that we can send the new or improved design.
Thanks

**Comment by hrmoh** [comment]
> Hello. I visited the Ganjar Museum website. In my opinion, it needs a revision in the design.
> So please create a new branch so that we can send the new or improved design.
> Thanks

Hi Dear Ehsan,
Although I guess it could be done forking the project, as I trust you and liked your previous contribution very much, I promoted your user to be Admin in this project, so you can do whatever you want your way.
Good Luck!
